// <auto-generated />
namespace SwirlFeed.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAccount_ClosedPropInUserTbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAccount_ClosedPropInUserTbl));
        
        string IMigrationMetadata.Id
        {
            get { return "201708300422494_AddAccount_ClosedPropInUserTbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
