// <auto-generated />
namespace SwirlFeed.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFriendsTblFor2nd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFriendsTblFor2nd));
        
        string IMigrationMetadata.Id
        {
            get { return "201708311945113_AddFriendsTblFor2nd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
